In [8]:
#RRF
import numpy as np

def rref(matrix):
    A = np.array(matrix, dtype=float)
    rows, cols = A.shape
    r = 0
    for c in range(cols):
        if r >= rows:
            break
        pivot = np.argmax(np.abs(A[r:rows, c])) + r
        if np.isclose(A[pivot, c], 0):
            continue
        A[[r, pivot]] = A[[pivot, r]]
        A[r] = A[r] / A[r, c]
        for i in range(rows):
            if i != r:
                A[i] = A[i] - A[i, c] * A[r]
        r += 1
    return A

print("Module 12: Row Reduced Echelon Form (RREF)")
print("=" * 50)

# Example matrix
matrix = [
    [1.0, 2.0, -1.0, -4.0],
    [2.0, 3.0, -1.0, -11.0],
    [-2.0, 0.0, -3.0, 22.0]
]

print("Input matrix:")
for row in matrix:
    print(row)

rref_matrix = rref(matrix)

print("\nRow Reduced Echelon Form:")
for row in rref_matrix:
    print(row)

with open('output_module12.txt', 'w') as f:
    f.write("Module 12: Row Reduced Echelon Form (RREF)\n")
    f.write("=" * 50 + "\n")
    f.write("Input matrix:\n")
    for row in matrix:
        f.write(f"{row}\n")
    f.write("\nRow Reduced Echelon Form:\n")
    for row in rref_matrix:
        f.write(f"{row}\n")


Module 12: Row Reduced Echelon Form (RREF)
Input matrix:
[1.0, 2.0, -1.0, -4.0]
[2.0, 3.0, -1.0, -11.0]
[-2.0, 0.0, -3.0, 22.0]

Row Reduced Echelon Form:
[ 1.  0.  0. -8.]
[0. 1. 0. 1.]
[ 0.  0.  1. -2.]


In [6]:
#Cholesky deomposiyion
import math

def cholesky_decomposition(A):
    n = len(A)
    L = [[0.0] * n for _ in range(n)]

    for i in range(n):
        for j in range(i + 1):
            sum_val = sum(L[i][k] * L[j][k] for k in range(j))
            if i == j:
                L[i][i] = math.sqrt(A[i][i] - sum_val)
            else:
                L[i][j] = (A[i][j] - sum_val) / L[j][j]
    return L

print("Module 3: Cholesky Decomposition")
print("=" * 50)

n = 3
A = [
    [4.0, 2.0, 1.0],
    [2.0, 5.0, 3.0],
    [1.0, 3.0, 6.0]
]

print(f"Input: {n}x{n} symmetric positive definite matrix")
print("Matrix A:")
for row in A:
    print(row)

L = cholesky_decomposition(A)

print("\nCholesky Lower Triangular Matrix L:")
for row in L:
    print(row)

with open('output_module3.txt', 'w') as f:
    f.write("Module 3: Cholesky Decomposition\n")
    f.write("=" * 50 + "\n")
    f.write(f"Input: {n}x{n} symmetric positive definite matrix\n")
    f.write("Matrix A:\n")
    for row in A:
        f.write(f"{row}\n")
    f.write("\nCholesky Lower Triangular Matrix L:\n")
    for row in L:
        f.write(f"{row}\n")


Module 3: Cholesky Decomposition
Input: 3x3 symmetric positive definite matrix
Matrix A:
[4.0, 2.0, 1.0]
[2.0, 5.0, 3.0]
[1.0, 3.0, 6.0]

Cholesky Lower Triangular Matrix L:
[2.0, 0.0, 0.0]
[1.0, 2.0, 0.0]
[0.5, 1.25, 2.0463381929681126]


In [7]:
#Gaussian elimination
def gaussian_elimination(A, n):
    for k in range(n):
        if A[k][k] == 0:
            for i in range(k + 1, n):
                if A[i][k] != 0:
                    A[k], A[i] = A[i], A[k]
                    break
        for i in range(k + 1, n):
            factor = A[i][k] / A[k][k]
            for j in range(k, n + 1):
                A[i][j] -= factor * A[k][j]
    return A

print("Module 11: Gaussian Elimination")
print("=" * 50)

n = 3
A = [
    [2.0, 1.0, -1.0, 8.0],
    [-3.0, -1.0, 2.0, -11.0],
    [-2.0, 1.0, 2.0, -3.0]
]

print(f"Input: {n} variables")
print("Augmented matrix:")
for row in A:
    print(row)

result = gaussian_elimination(A, n)

print("\nUpper Triangular Matrix:")
for row in result:
    print(row)

with open('output_module11.txt', 'w') as f:
    f.write("Module 11: Gaussian Elimination\n")
    f.write("=" * 50 + "\n")
    f.write(f"Input: {n} variables\n")
    f.write("Augmented matrix:\n")
    for row in [[2.0, 1.0, -1.0, 8.0], [-3.0, -1.0, 2.0, -11.0], [-2.0, 1.0, 2.0, -3.0]]:
        f.write(f"{row}\n")
    f.write("\nUpper Triangular Matrix:\n")
    for row in result:
        f.write(f"{row}\n")


Module 11: Gaussian Elimination
Input: 3 variables
Augmented matrix:
[2.0, 1.0, -1.0, 8.0]
[-3.0, -1.0, 2.0, -11.0]
[-2.0, 1.0, 2.0, -3.0]

Upper Triangular Matrix:
[2.0, 1.0, -1.0, 8.0]
[0.0, 0.5, 0.5, 1.0]
[0.0, 0.0, -1.0, 1.0]


In [9]:
#gram schimdt
import numpy as np

def gram_schmidt(V):
    U = []
    for v in V:
        v = np.array(v, dtype=float)
        u = v.copy()
        for prev_u in U:
            proj = np.dot(v, prev_u) / np.dot(prev_u, prev_u)
            u = u - proj * prev_u
        U.append(u)
    return U

V = [
    [1, 1, 0],
    [1, 0, 1],
    [0, 1, 1]
]

print("Module 13: Gram-Schmidt Process (Hardcoded Example)")
print("=" * 50)
print("Input basis vectors:")
for i, v in enumerate(V, 1):
    print(f"v{i} = {v}")

U = gram_schmidt(V)

print("\nOrthogonal vectors (Output):")
for i, u in enumerate(U, 1):
    print(f"u{i} = {u}")

with open('output_module13.txt', 'w') as f:
    f.write("Module 13: Gram-Schmidt Process \n")
    f.write("=" * 50 + "\n")
    f.write("Input basis vectors:\n")
    for i, v in enumerate(V, 1):
        f.write(f"v{i} = {v}\n")
    f.write("\nOrthogonal vectors (Output):\n")
    for i, u in enumerate(U, 1):
        f.write(f"u{i} = {u}\n")


Module 13: Gram-Schmidt Process (Hardcoded Example)
Input basis vectors:
v1 = [1, 1, 0]
v2 = [1, 0, 1]
v3 = [0, 1, 1]

Orthogonal vectors (Output):
u1 = [1. 1. 0.]
u2 = [ 0.5 -0.5  1. ]
u3 = [-0.66666667  0.66666667  0.66666667]
